name: Build and Zip to Azure Storage

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release'
        required: false

jobs:
  merge-master-back-to-dev:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MAINTAIN_TOKEN }}
          ref: master
      - name: Checkout dev
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MAINTAIN_TOKEN }}
          ref: dev
      - name: Merge master -> dev
        uses: devmasx/merge-branch@a1752b9ba42bb417ec19be7dc974e2faf77d3ef2
        with:
          type: now
          from_branch: master
          target_branch: dev
          github_token: ${{ secrets.MAINTAIN_TOKEN }}
  bump-version:
    needs: merge-master-back-to-dev
    runs-on: ubuntu-20.04
    outputs:
      prev_version: ${{ steps.bump_version_step.outputs.prev_version }}
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MAINTAIN_TOKEN }}
          ref: dev
      - name: Bump version
        id: bump_version_step
        run: |
          npm config set git-tag-version false
          PREV_PACKAGE_VERSION=$(node -p "require('./package.json').version")
          npm version minor
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
          echo "::set-output name=prev_version:${PREV_PACKAGE_VERSION}"
      - name: Update version in files
        env:
          VERSION: ${{ env.PACKAGE_VERSION }}
        run: |
          npm install --no-package-lock --no-save replace-in-file@6.2.0
          node ./.github/scripts/update-version-in-files.js
          npx grunt wp_readme
      - name: Check if readme is updated
        env:
          VERSION: ${{ env.PACKAGE_VERSION }}
        run: |
          npm install --no-package-lock --no-save marked@2.0.6
          node ./.github/scripts/get-changelog-from-readme-txt.js
      - name: Push new version to dev
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
          MAINTAIN_EMAIL: ${{ secrets.MAINTAIN_EMAIL }}
          MAINTAIN_USERNAME: ${{ secrets.MAINTAIN_USERNAME }}
        run: |
          bash "${GITHUB_WORKSPACE}/.github/scripts/commit-push-bump.sh"
  publish:
    needs: bump-version
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MAINTAIN_TOKEN }}
          ref: master
      - name: Merge dev -> master
        uses: devmasx/merge-branch@a1752b9ba42bb417ec19be7dc974e2faf77d3ef2
        with:
          type: now
          from_branch: dev
          target_branch: master
          github_token: ${{ secrets.MAINTAIN_TOKEN }}
      - name: Checkout updated master branch
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MAINTAIN_TOKEN }}
          ref: master
      - name: Install Dependencies
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
          npm ci
      - name: Build
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
        run: npm run zip
      - name: Upload zip file to GitHub Actions artifact
        uses: actions/upload-artifact@v2
        with:
          name: hello-joint.${{ env.PACKAGE_VERSION }}
          path: hello-joint.*.zip
          if-no-files-found: error
      - name: Create tag
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
          MAINTAIN_EMAIL: ${{ secrets.MAINTAIN_EMAIL }}
          MAINTAIN_USERNAME: ${{ secrets.MAINTAIN_USERNAME }}
        run: |
          bash "${GITHUB_WORKSPACE}/.github/scripts/create-git-tag.sh"
      - name: Reach changelog from readme
        env:
          VERSION: ${{ env.PACKAGE_VERSION }}
        run: |
          npm install --no-package-lock --no-save marked@2.0.6
          node ./.github/scripts/get-changelog-from-readme-txt.js
      - name: Create GitHub reelease
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.PACKAGE_VERSION }}
          files: hello-joint.*.zip
          body_path: temp-changelog-from-readme.txt
        env:
          GITHUB_TOKEN: ${{ secrets.MAINTAIN_TOKEN }}
